class PlaceType {
    static get TYPE_OTHER(): number { return 0; }
    static get TYPE_ACCOUNTING(): number { return 1; }
    static get TYPE_AIRPORT(): number { return 2; }
    static get TYPE_AMUSEMENT_PARK(): number { return 3; }
    static get TYPE_AQUARIUM(): number { return 4; }
    static get TYPE_ART_GALLERY(): number { return 5; }
    static get TYPE_ATM(): number { return 6; }
    static get TYPE_BAKERY(): number { return 7; }
    static get TYPE_BANK(): number { return 8; }
    static get TYPE_BAR(): number { return 9; }
    static get TYPE_BEAUTY_SALON(): number { return 10; }
    static get TYPE_BICYCLE_STORE(): number { return 11; }
    static get TYPE_BOOK_STORE(): number { return 12; }
    static get TYPE_BOWLING_ALLEY(): number { return 13; }
    static get TYPE_BUS_STATION(): number { return 14; }
    static get TYPE_CAFE(): number { return 15; }
    static get TYPE_CAMPGROUND(): number { return 16; }
    static get TYPE_CAR_DEALER(): number { return 17; }
    static get TYPE_CAR_RENTAL(): number { return 18; }
    static get TYPE_CAR_REPAIR(): number { return 19; }
    static get TYPE_CAR_WASH(): number { return 20; }
    static get TYPE_CASINO(): number { return 21; }
    static get TYPE_CEMETERY(): number { return 22; }
    static get TYPE_CHURCH(): number { return 23; }
    static get TYPE_CITY_HALL(): number { return 24; }
    static get TYPE_CLOTHING_STORE(): number { return 25; }
    static get TYPE_CONVENIENCE_STORE(): number { return 26; }
    static get TYPE_COURTHOUSE(): number { return 27; }
    static get TYPE_DENTIST(): number { return 28; }
    static get TYPE_DEPARTMENT_STORE(): number { return 29; }
    static get TYPE_DOCTOR(): number { return 30; }
    static get TYPE_ELECTRICIAN(): number { return 31; }
    static get TYPE_ELECTRONICS_STORE(): number { return 32; }
    static get TYPE_EMBASSY(): number { return 33; }
    static get TYPE_ESTABLISHMENT(): number { return 34; }
    static get TYPE_FINANCE(): number { return 35; }
    static get TYPE_FIRE_STATION(): number { return 36; }
    static get TYPE_FLORIST(): number { return 37; }
    static get TYPE_FOOD(): number { return 38; }
    static get TYPE_FUNERAL_HOME(): number { return 39; }
    static get TYPE_FURNITURE_STORE(): number { return 40; }
    static get TYPE_GAS_STATION(): number { return 41; }
    static get TYPE_GENERAL_CONTRACTOR(): number { return 42; }
    static get TYPE_GROCERY_OR_SUPERMARKET(): number { return 43; }
    static get TYPE_GYM(): number { return 44; }
    static get TYPE_HAIR_CARE(): number { return 45; }
    static get TYPE_HARDWARE_STORE(): number { return 46; }
    static get TYPE_HEALTH(): number { return 47; }
    static get TYPE_HINDU_TEMPLE(): number { return 48; }
    static get TYPE_HOME_GOODS_STORE(): number { return 49; }
    static get TYPE_HOSPITAL(): number { return 50; }
    static get TYPE_INSURANCE_AGENCY(): number { return 51; }
    static get TYPE_JEWELRY_STORE(): number { return 52; }
    static get TYPE_LAUNDRY(): number { return 53; }
    static get TYPE_LAWYER(): number { return 54; }
    static get TYPE_LIBRARY(): number { return 55; }
    static get TYPE_LIQUOR_STORE(): number { return 56; }
    static get TYPE_LOCAL_GOVERNMENT_OFFICE(): number { return 57; }
    static get TYPE_LOCKSMITH(): number { return 58; }
    static get TYPE_LODGING(): number { return 59; }
    static get TYPE_MEAL_DELIVERY(): number { return 60; }
    static get TYPE_MEAL_TAKEAWAY(): number { return 61; }
    static get TYPE_MOSQUE(): number { return 62; }
    static get TYPE_MOVIE_RENTAL(): number { return 63; }
    static get TYPE_MOVIE_THEATER(): number { return 64; }
    static get TYPE_MOVING_COMPANY(): number { return 65; }
    static get TYPE_MUSEUM(): number { return 66; }
    static get TYPE_NIGHT_CLUB(): number { return 67; }
    static get TYPE_PAINTER(): number { return 68; }
    static get TYPE_PARK(): number { return 69; }
    static get TYPE_PARKING(): number { return 70; }
    static get TYPE_PET_STORE(): number { return 71; }
    static get TYPE_PHARMACY(): number { return 72; }
    static get TYPE_PHYSIOTHERAPIST(): number { return 73; }
    static get TYPE_PLACE_OF_WORSHIP(): number { return 74; }
    static get TYPE_PLUMBER(): number { return 75; }
    static get TYPE_POLICE(): number { return 76; }
    static get TYPE_POST_OFFICE(): number { return 77; }
    static get TYPE_REAL_ESTATE_AGENCY(): number { return 78; }
    static get TYPE_RESTAURANT(): number { return 79; }
    static get TYPE_ROOFING_CONTRACTOR(): number { return 80; }
    static get TYPE_RV_PARK(): number { return 81; }
    static get TYPE_SCHOOL(): number { return 82; }
    static get TYPE_SHOE_STORE(): number { return 83; }
    static get TYPE_SHOPPING_MALL(): number { return 84; }
    static get TYPE_SPA(): number { return 85; }
    static get TYPE_STADIUM(): number { return 86; }
    static get TYPE_STORAGE(): number { return 87; }
    static get TYPE_STORE(): number { return 88; }
    static get TYPE_SUBWAY_STATION(): number { return 89; }
    static get TYPE_SYNAGOGUE(): number { return 90; }
    static get TYPE_TAXI_STAND(): number { return 91; }
    static get TYPE_TRAIN_STATION(): number { return 92; }
    static get TYPE_TRAVEL_AGENCY(): number { return 93; }
    static get TYPE_UNIVERSITY(): number { return 94; }
    static get TYPE_VETERINARY_CARE(): number { return 95; }
    static get TYPE_ZOO(): number { return 96; }
    static get TYPE_ADMINISTRATIVE_AREA_LEVEL_1(): number { return 1001; }
    static get TYPE_ADMINISTRATIVE_AREA_LEVEL_2(): number { return 1002; }
    static get TYPE_ADMINISTRATIVE_AREA_LEVEL_3(): number { return 1003; }
    static get TYPE_COLLOQUIAL_AREA(): number { return 1004; }
    static get TYPE_COUNTRY(): number { return 1005; }
    static get TYPE_FLOOR(): number { return 1006; }
    static get TYPE_GEOCODE(): number { return 1007; }
    static get TYPE_INTERSECTION(): number { return 1008; }
    static get TYPE_LOCALITY(): number { return 1009; }
    static get TYPE_NATURAL_FEATURE(): number { return 1010; }
    static get TYPE_NEIGHBORHOOD(): number { return 1011; }
    static get TYPE_POLITICAL(): number { return 1012; }
    static get TYPE_POINT_OF_INTEREST(): number { return 1013; }
    static get TYPE_POST_BOX(): number { return 1014; }
    static get TYPE_POSTAL_CODE(): number { return 1015; }
    static get TYPE_POSTAL_CODE_PREFIX(): number { return 1016; }
    static get TYPE_POSTAL_TOWN(): number { return 1017; }
    static get TYPE_PREMISE(): number { return 1018; }
    static get TYPE_ROOM(): number { return 1019; }
    static get TYPE_ROUTE(): number { return 1020; }
    static get TYPE_STREET_ADDRESS(): number { return 1021; }
    static get TYPE_SUBLOCALITY(): number { return 1022; }
    static get TYPE_SUBLOCALITY_LEVEL_1(): number { return 1023; }
    static get TYPE_SUBLOCALITY_LEVEL_2(): number { return 1024; }
    static get TYPE_SUBLOCALITY_LEVEL_3(): number { return 1025; }
    static get TYPE_SUBLOCALITY_LEVEL_4(): number { return 1026; }
    static get TYPE_SUBLOCALITY_LEVEL_5(): number { return 1027; }
    static get TYPE_SUBPREMISE(): number { return 1028; }
    static get TYPE_SYNTHETIC_GEOCODE(): number { return 1029; }
    static get TYPE_TRANSIT_STATION(): number { return 1030; }

}